version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: task_splitter_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - ./backend:/app
      - ./.env:/app/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/task_splitter_development
      RAILS_ENV: development
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    stdin_open: true
    tty: true

  frontend:
    image: node:20
    working_dir: /app
    command: sh -c "yarn install && yarn dev --host 0.0.0.0"
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  postgres_data: